# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/gareth/dev/other/BSP-future-urban-growth/futurb/futurb_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FuturbDialogBase(object):
    def setupUi(self, FuturbDialogBase):
        FuturbDialogBase.setObjectName("FuturbDialogBase")
        FuturbDialogBase.resize(400, 300)
        self.button_box = QtWidgets.QDialogButtonBox(FuturbDialogBase)
        self.button_box.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.n_iterations = QtWidgets.QLineEdit(FuturbDialogBase)
        self.n_iterations.setGeometry(QtCore.QRect(210, 90, 161, 31))
        self.n_iterations.setText("")
        self.n_iterations.setObjectName("n_iterations")

        self.retranslateUi(FuturbDialogBase)
        self.button_box.accepted.connect(FuturbDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(FuturbDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(FuturbDialogBase)

    def retranslateUi(self, FuturbDialogBase):
        _translate = QtCore.QCoreApplication.translate
        FuturbDialogBase.setWindowTitle(_translate("FuturbDialogBase", "Future Urban Growth test."))
        self.n_iterations.setPlaceholderText(_translate("FuturbDialogBase", "n iterations"))
